# wandb 설정
wandb_group: "wandb_group"
wandb_name: "wandb_name"

# KFold 설정
kfold_n: 0

# 모델 관련 설정
pretrained: false
pretrained_dir: "/data/ephemeral/home/saved_model/best_model.pth"

# 하이퍼파라미터 설정
batch_size: 16
batch_size_valid: 1
learning_rate: 0.0001
random_seed: 42
num_epochs: 100
val_every: 5
device: "cuda"

# 데이터 및 저장 경로 설정
data_root: "/data/ephemeral/beomjo/level2-cv-semanticsegmentation-team/data"
image_root: "/data/ephemeral/beomjo/level2-cv-semanticsegmentation-team/data/train/DCM"
label_root: "/data/ephemeral/beomjo/level2-cv-semanticsegmentation-team/kfold_splits/"
test_image_root: "/data/ephemeral/home/data/test/DCM"
saved_dir: "/data/ephemeral/home/saved_model"

# 클래스 정보
classes:
  - "finger-1"
  - "finger-2"
  - "finger-3"
  - "finger-4"
  - "finger-5"
  - "finger-6"
  - "finger-7"
  - "finger-8"
  - "finger-9"
  - "finger-10"
  - "finger-11"
  - "finger-12"
  - "finger-13"
  - "finger-14"
  - "finger-15"
  - "finger-16"
  - "finger-17"
  - "finger-18"
  - "finger-19"
  - "Trapezium"
  - "Trapezoid"
  - "Capitate"
  - "Hamate"
  - "Scaphoid"
  - "Lunate"
  - "Triquetrum"
  - "Pisiform"
  - "Radius"
  - "Ulna"

# 색상 팔레트
palette:
  - [220, 20, 60]
  - [119, 11, 32]
  - [0, 0, 142]
  - [0, 0, 230]
  - [106, 0, 228]
  - [0, 60, 100]
  - [0, 80, 100]
  - [0, 0, 70]
  - [0, 0, 192]
  - [250, 170, 30]
  - [100, 170, 30]
  - [220, 220, 0]
  - [175, 116, 175]
  - [250, 0, 30]
  - [165, 42, 42]
  - [255, 77, 255]
  - [0, 226, 252]
  - [182, 182, 255]
  - [0, 82, 0]
  - [120, 166, 157]
  - [110, 76, 0]
  - [174, 57, 255]
  - [199, 100, 0]
  - [72, 0, 118]
  - [255, 179, 240]
  - [0, 125, 92]
  - [209, 0, 151]
  - [188, 208, 182]
  - [0, 220, 176]
