image_root: /data/ephemeral/home/data/test/DCM

root_path: /data/ephemeral/home/github/mmsegmentation
config_path: /data/ephemeral/home/github/mmsegmentation/configs/config.py

CLASSES: [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
]

batch_size: 2
num_workers: 2

threshold: 0.5

model_paths:
  512: []
  1024: []
  1536: []
  2048: ['/data/ephemeral/home/github/mmsegmentation/work_dir/segformer/fold0/7lg1mghx/best_mDice_epoch_33.pth', 
        '/data/ephemeral/home/github/mmsegmentation/work_dir/segformer/fold1/20241125_150126/best_mDice_epoch_1.pth',
        '/data/ephemeral/home/github/mmsegmentation/work_dir/segformer/fold2/epoch_50.pth',
        '/data/ephemeral/home/github/mmsegmentation/work_dir/segformer/fold3/epoch_50.pth',
        '/data/ephemeral/home/github/mmsegmentation/work_dir/segformer/fold4/epoch_50.pth']

save_dir: ./soft_ensemble
output_name: soft_voting_segfomer_2048_fold01234_ver2.csv