program: tools/train.py
method: bayes  # 탐색 방법: 'grid', 'random', 'bayes'
metric:
  name: mDice  # 최적화할 지표
  goal: maximize   # 최대화
parameters:
  lr:
    distribution: float_uniform  # 부동소수점 값으로 지정
    min: 1e-5       # 최소 학습률
    max: 1e-3       # 최대 학습률
  weight_decay:
    distribution: float_uniform  # 부동소수점 값으로 지정
    min: 1e-4       # 최소 Weight Decay
    max: 1e-2       # 최대 Weight Decay
early_terminate:
  type: hyperband
  s: 3
  eta: 2
  max_iter: 10