# 절대 경로로 데이터셋 위치 지정
path: /home/sh/bootcamp/yolo_dataset  # 데이터셋의 루트 디렉토리
train: images/train  # train 폴더 경로 (path에 대한 상대 경로)
val: images/val     # validation 폴더 경로 (path에 대한 상대 경로)

# Classes
nc: 29  # number of classes
names: # class names
  0: finger-1
  1: finger-2
  2: finger-3
  3: finger-4
  4: finger-5
  5: finger-6
  6: finger-7
  7: finger-8
  8: finger-9
  9: finger-10
  10: finger-11
  11: finger-12
  12: finger-13
  13: finger-14
  14: finger-15
  15: finger-16
  16: finger-17
  17: finger-18
  18: finger-19
  19: Trapezium
  20: Trapezoid
  21: Capitate
  22: Hamate
  23: Scaphoid
  24: Lunate
  25: Triquetrum
  26: Pisiform
  27: Radius
  28: Ulna

# Training settings
task: segment